const avatar = (gender: "men" | "women", n: number) =>
  `https://randomuser.me/api/portraits/${gender}/${n}.jpg`;

export const SEED_PROFILES = [
  // Runners
  {
    fullName: "Kwame Asante",
    email: "kwame.asante@st.knust.edu.gh",
    phone: "+233241000001",
    photoUrl: avatar("men", 11),
    bio: "Final year CS student. Fast on two wheels, reliable on foot.",
    role: "runner" as const,
    studentIdVerified: true,
    campus: "KNUST",
    rating: "4.90",
    totalJobs: 87,
  },
  {
    fullName: "Abena Mensah",
    email: "abena.mensah@st.knust.edu.gh",
    phone: "+233241000002",
    photoUrl: avatar("women", 22),
    bio: "Nursing student. I run errands between lectures. DM anytime.",
    role: "runner" as const,
    studentIdVerified: true,
    campus: "KNUST",
    rating: "4.75",
    totalJobs: 64,
  },
  {
    fullName: "Yaw Darko",
    email: "yaw.darko@st.knust.edu.gh",
    phone: "+233241000003",
    photoUrl: avatar("men", 33),
    bio: "Mechanical Engineering. Motorbike delivery across campus.",
    role: "runner" as const,
    studentIdVerified: false,
    campus: "KNUST",
    rating: "4.60",
    totalJobs: 43,
  },
  {
    fullName: "Ama Osei",
    email: "ama.osei@st.knust.edu.gh",
    phone: "+233241000004",
    photoUrl: avatar("women", 44),
    bio: "Business student turned delivery queen. No quest too small.",
    role: "runner" as const,
    studentIdVerified: true,
    campus: "KNUST",
    rating: "4.85",
    totalJobs: 112,
  },
  {
    fullName: "Kofi Boateng",
    email: "kofi.boateng@st.knust.edu.gh",
    phone: "+233241000005",
    photoUrl: avatar("men", 55),
    bio: "Architecture student. I know every corner of this campus.",
    role: "runner" as const,
    studentIdVerified: true,
    campus: "KNUST",
    rating: "4.70",
    totalJobs: 58,
  },
  {
    fullName: "Efua Ankrah",
    email: "efua.ankrah@st.knust.edu.gh",
    phone: "+233241000006",
    photoUrl: avatar("women", 12),
    bio: "Pharmacy student. Accurate, careful, and always on time.",
    role: "runner" as const,
    studentIdVerified: false,
    campus: "KNUST",
    rating: "4.50",
    totalJobs: 29,
  },
  {
    fullName: "Kwabena Poku",
    email: "kwabena.poku@st.knust.edu.gh",
    phone: "+233241000007",
    photoUrl: avatar("men", 7),
    bio: "Mathematics. Precision in numbers, precision in delivery.",
    role: "runner" as const,
    studentIdVerified: true,
    campus: "KNUST",
    rating: "4.95",
    totalJobs: 145,
  },
  {
    fullName: "Adwoa Frimpong",
    email: "adwoa.frimpong@st.knust.edu.gh",
    phone: "+233241000008",
    photoUrl: avatar("women", 68),
    bio: "Law student. I handle your quests with legal precision.",
    role: "runner" as const,
    studentIdVerified: true,
    campus: "KNUST",
    rating: "4.80",
    totalJobs: 76,
  },
  // Requesters
  {
    fullName: "Nana Adu",
    email: "nana.adu@st.knust.edu.gh",
    phone: "+233241000009",
    photoUrl: avatar("men", 18),
    bio: "Level 200 EE student. Too many labs, too little time.",
    role: "requester" as const,
    studentIdVerified: true,
    campus: "KNUST",
    rating: "4.40",
    totalJobs: 22,
  },
  {
    fullName: "Akosua Amponsah",
    email: "akosua.amponsah@st.knust.edu.gh",
    phone: "+233241000010",
    photoUrl: avatar("women", 31),
    bio: "Chemistry student. Prefer to stay in the lab.",
    role: "requester" as const,
    studentIdVerified: false,
    campus: "KNUST",
    rating: "4.20",
    totalJobs: 15,
  },
  {
    fullName: "Fiifi Baidoo",
    email: "fiifi.baidoo@st.knust.edu.gh",
    phone: "+233241000011",
    photoUrl: avatar("men", 42),
    bio: "Computer Science. Always coding, rarely cooking.",
    role: "requester" as const,
    studentIdVerified: true,
    campus: "KNUST",
    rating: "4.60",
    totalJobs: 37,
  },
  {
    fullName: "Maame Serwah",
    email: "maame.serwah@st.knust.edu.gh",
    phone: "+233241000012",
    photoUrl: avatar("women", 57),
    bio: "Medicine student. On-call 24/7, quests save my day.",
    role: "requester" as const,
    studentIdVerified: true,
    campus: "KNUST",
    rating: "4.80",
    totalJobs: 51,
  },
  // Both roles
  {
    fullName: "Kweku Asiedu",
    email: "kweku.asiedu@st.knust.edu.gh",
    phone: "+233241000013",
    photoUrl: avatar("men", 63),
    bio: "Hustle hard, study harder. I run and I post.",
    role: "both" as const,
    studentIdVerified: true,
    campus: "KNUST",
    rating: "4.65",
    totalJobs: 89,
  },
  {
    fullName: "Araba Nyarko",
    email: "araba.nyarko@st.knust.edu.gh",
    phone: "+233241000014",
    photoUrl: avatar("women", 9),
    bio: "Textile Engineering. I run quests to fund my fabric addiction.",
    role: "both" as const,
    studentIdVerified: false,
    campus: "KNUST",
    rating: "4.55",
    totalJobs: 47,
  },
  {
    fullName: "Kojo Ofori",
    email: "kojo.ofori@st.knust.edu.gh",
    phone: "+233241000015",
    photoUrl: avatar("men", 27),
    bio: "Civil Engineering. Built for endurance. I'll carry your load.",
    role: "both" as const,
    studentIdVerified: true,
    campus: "KNUST",
    rating: "4.72",
    totalJobs: 93,
  },
  {
    fullName: "Akua Bonsu",
    email: "akua.bonsu@st.knust.edu.gh",
    phone: "+233241000016",
    photoUrl: avatar("women", 38),
    bio: "Social Work student. Community-minded runner.",
    role: "both" as const,
    studentIdVerified: true,
    campus: "KNUST",
    rating: "4.88",
    totalJobs: 120,
  },
  {
    fullName: "Nii Laryea",
    email: "nii.laryea@st.knust.edu.gh",
    phone: "+233241000017",
    photoUrl: avatar("men", 50),
    bio: "Statistics. Probability that I deliver on time: 99%.",
    role: "both" as const,
    studentIdVerified: true,
    campus: "KNUST",
    rating: "4.91",
    totalJobs: 137,
  },
  {
    fullName: "Esi Quansah",
    email: "esi.quansah@st.knust.edu.gh",
    phone: "+233241000018",
    photoUrl: avatar("women", 74),
    bio: "Food Science student. I know good food spots on campus.",
    role: "both" as const,
    studentIdVerified: false,
    campus: "KNUST",
    rating: "4.45",
    totalJobs: 32,
  },
  {
    fullName: "Ato Mensah",
    email: "ato.mensah@st.knust.edu.gh",
    phone: "+233241000019",
    photoUrl: avatar("men", 81),
    bio: "Philosophy student. Thinking and running aren't mutually exclusive.",
    role: "both" as const,
    studentIdVerified: true,
    campus: "KNUST",
    rating: "4.30",
    totalJobs: 18,
  },
  {
    fullName: "Abiba Alhassan",
    email: "abiba.alhassan@st.knust.edu.gh",
    phone: "+233241000020",
    photoUrl: avatar("women", 60),
    bio: "Development Studies. Running quests builds community.",
    role: "both" as const,
    studentIdVerified: true,
    campus: "KNUST",
    rating: "4.78",
    totalJobs: 66,
  },
];
